from collections import defaultdict
import asyncio


CHAINS_DATA = {
    'ethereum': {'explorer': 'https://etherscan.io/tx/'},
    'base': {'explorer': 'https://basescan.org/tx/'},
    'arbitrum': {'explorer': 'https://arbiscan.io/tx/'},
    'zksync': {'explorer': 'https://era.zksync.network/tx/'},
    'optimism': {'explorer': 'https://optimistic.etherscan.io/tx/'},
    'scroll': {'explorer': 'https://scrollscan.com/tx/'},
    'nova': {'explorer': 'https://nova-explorer.arbitrum.io/tx/'},
    'linea': {'explorer': 'https://lineascan.build/tx/'},
    'bsc': {'explorer': 'https://bscscan.com/tx/'},
    'polygon': {'explorer': 'https://polygonscan.com/tx/'},
    'celo': {'explorer': 'https://celoscan.io/tx/'},
    'moonbeam': {'explorer': 'https://moonscan.io/tx/'},
    'fantom': {'explorer': 'https://ftmscan.com/tx/'},
    'avax': {'explorer': 'https://snowtrace.io/tx/'},
    'zora': {'explorer': 'https://explorer.zora.energy/tx/'},
    'solana': {'explorer': 'https://solscan.io/tx/'},
    'eclipse': {'explorer': 'https://eclipsescan.xyz/tx/'},
}

SOL_TOKEN_ADDRESSES = {
    "SOL": "So11111111111111111111111111111111111111112",
    "USDC": "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
    "USDT": "Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB",
    "WBTC": "3NZ9JMVBmGAqocybic2c7LQCJScmgsAZ6vQqTDzcqmJh",
    "WETH": "7vfCXTUXx5WJV5JADk17DUJ4ksgau7utNKj4b963voxs",
    "JTO": "jtojtomepa8beP8AuQc6eXt5FriJwfFMwQx2v2f9mCL",
    "JUP": "JUPyiwrYJFskUPiHa7hkeR8VUtAeFoSYbKedZNsDvCN",
    "KMNO": "KMNo3nJsBXfcpJTVhZcXLW7RmTwTt4GVFE7suUBo9sS",
    "PYTH": "HZ1JovNiVvGrGNiiYvEozEVgZ58xaU3RKwX8eACQBCt3",
    "TRUMP": "6p6xgHyF7AeE6TZkSmFsko444wqoP15icUSqi2jfGiPN",
    "RAY": "4k3Dyjzvzp8eMZWUXbBCjEvwSkkk59S5iCNLY3QrkX6R",
    "LAUNCHCOIN": "Ey59PH7Z4BFU4HjyKnyMdWt5GGN76KazTAwQihoUXRnk",
    "WIF": "EKpQGSJtjMFqKZ9KQanSqYXRcF8fBopzLHYxdM65zcjm",
    "ai16z": "HeLp6NuQkmYB4pYWo2zYs22mESHXPQYzXbB8n4V98jwC",
    "PENGU": "2zMMhcVQEXDtdE6vsFS7S7D5oUodfJHE8vd1gnBouauv",
    "POPCAT": "7GCihgDB8fe6KNjn2MYtkzZcRjQy3t9GHdC8uHYmW2hr",
    "Fartcoin": "9BB6NFEcjBCtnNLFko2FqVQBq8HHM13kCyYcdQbgpump",
    "JITOSOL": "J1toso1uCk3RLmjorhTtrVwY9HJ7X8V9yYac6Y7kGCPn",
    "PYUSD": "2b1kV6DkPAnxd5ixfnxCpjxmKwqjjaYmCZfHsFu24GXo",
    "BONK": "DezXAZ8z7PnrnRJjz3wXBoRgixCa6xjnB7YaB1pPB263",
    "cbBTC": "cbbtcf3aa214zXHbiAZQwf4122FBYbraNdFqgw4iMij",
    "JLP": "27G8MtK7VtTcCHkpASjSDdkWWYfoqT6ggEuKidVJidD4",
    "GOOGLx": "XsCPL9dNWBMvFtTmwcCA5v3xWPSMEBCszbQdiLLq6aN",
    "COINx": "Xs7ZdzSHLU9ftNJsii5fCeJhoRWSC32SQGzGQtePxNu",
    "SPYx": "XsoCS1TfEyfFhfvj8EtZ528L3CaKBDBRqRapnBbDF2W",
    "NVDAx": "Xsc9qvGR1efVDFGLrVsmkzv3qi45LTBjeUKSPmx9qEh",
    "METAx": "Xsa62P5mvPszXL1krVUnU5ar38bBSVcWAB6fmPCo5Zu",
    "TSLAx": "XsDoVfqeBukxuZHWhdvWHBhgEHjGNst4MLodqsJHzoB",
    "CRCLx": "XsueG8BtpquVJX9LVLLEGuViXUungE6WmK5YZ3p3bd1",
    "MSTRx": "XsP7xzNPvEHS1m6qfanPUGjNmdnmsLKEoNAnHjdxxyZ",
    "AMZNx": "Xs3eBt7uRfJX8QUs4suhyU8p2M6DoUDrJyWBa8LLZsg",
    "AAPLx": "XsbEhLAtcf6HdfpFZ5xEMdqW8nfAvcsP5bdudRLJzJp",
    "QQQx": "Xs8S1uUs1zvS2p7iwtsG3b6fkhpvmwz4GYU3gWAmWHZ",
    "USELESS": "Dz9mQ9NzkBcCsuGPFJ3r1bS4wgqKMHBPiVuniW8Mbonk",
    "1": "GMvCfcZg8YvkkQmwDaAzCtHDrrEtgE74nQpQ7xNabonk",
    "KORI": "HtTYHz1Kf3rrQo6AqDLmss7gq5WrkWAaXn3tupUZbonk",
    "AOL": "2oQNkePakuPbHzrVVkQ875WHeewLHCd2cAwfwiLQbonk",
    "67": "76rTxzztXjJe7AUaBi7jQ5J61MFgpQgB4Cc934sWbonk",
    "URA": "BwTu5zJqEyLYawwYoGTWT7UxC85eLYQWRcta1GiEbonk",
    "MOMO": "G4zwEA9NSd3nMBbEj31MMPq2853Brx2oGsKzex3ebonk",
    "memecoin": "4daoTLufDmV3ods48Zh8rymaZKBLtgEvuH9qALYLbonk",
    "Ani": "9tqjeRS1swj36Ee5C1iGiwAxjQJNGAVCzaTLwFY8bonk",
    "BUNDLE": "YJWeeW5JBAQJuBrPLZxb42UeFMAAGtfC4NDvNRPbonk",
    "NYLA": "3HeUeL8ru8DFfRRQGnE11vGrDdNUzqVwBW8hyYHBbonk",
    "旺柴": "83kGGSggYGP2ZEEyvX54SkZR1kFn84RgGCDyptbDbonk",
    "GOLDCARD": "GsSUx3qENEAn5MDQLGYHYs7ThtPXsnwCkKwqv1ZWbonk",
    "aircoin": "GpdRNotihwXZJ3z3y6yCRAhecFrALc4J8SX92pxnbonk",
    "FARTLESS": "FyrBf5xKg5EwKZ9pHvSpJeLLuCWBicTpm3VvZcsibonk",
    "sendit": "6nz8p3Mzw4q4rhHZFbaLAqGv48Ab2PRPSYW1o8YHbonk",
    "DORK": "A4RfnhcD1hk2QiVUx3TTtR7Af2RkgjvyJMcnogj9bonk",
    "LetsBONK": "CDBdbNqmrLu1PcgjrFG52yxg71QnFhBZcUE6PSFdbonk",
    "Monkey": "CNNQZyEWfz9mDBRCiRNwjaUvMaLnaRWem8HeJYh7bonk",
    "200M": "4ujx7weoPYqFyHkk3px1QWM3HSfG6oBxbyfBY4HHbonk",
    "underdog": "B4aJyVCibxP1J95RccZ57DPJWEfkkzUDbm9DuFD9bonk",
    "CAPY": "7VENy6wCjBChAMGpjPQCPYJDeYJGFr5NZUxk7uQ7bonk",
    "Hosico": "9wK8yN6iz1ie5kEJkvZCTxyN1x5sTdNfx8yeMY8Ebonk",
    "BlueChip": "DHJVYXsikcimtcVo49FAZqYd1XPYPaXezYhbKArJbonk",
    "RT": "3uxMtF7dT2VSvRFkrLf9Gqm4nDDy2J5RBEXCQpjubonk",
    "IKUN": "AtortPA9SVbkKmdzu5zg4jxgkR4howvPshorA9jYbonk",
    "SSX": "2EyNf2PCNT7eQ9ag1RDXw3qn3Cy22WdTA9T6HKDebonk",
    "Valentine": "9GtvcnDUvGsuibktxiMjLQ2yyBq5akUahuBs8yANbonk",
    "AI": "7tAnusL3srXjzEriVL86a23KgwDZKXJTZ2ezEUubonk",
    "JET2": "Bf5uwQqUmtHLPYmGvs4z3Y56QtXgv6ApwQWo4aVrbonk",
    "PSA": "3jqtFb6TNfddCtuY5ixVmari8PGaqne1NRwRqhUqbonk",
    "LuckyCoin": "3BtunCQ3KdpsYtXQU9SmkGopnDkaQHuEgG14Dy1Lbonk",
    "VCM": "GMcThHFBnN6zjB2Mvbgdi19A2m35g81y7B1AKhgGbonk",
    "TRUST": "F5sc3CGLmKueyUqaCkwopo9u61HsgpmJc8Cmc9xibonk",
    "DETECTIVE": "9X45NjtGbGo9zdCFmMyqZyNzC6Wa67KFbfvGc8nubonk",
    "Scam": "9mNjA6BizTwpvd4DS3o7BjwZ6aPM9DC2jLHS7JFGbonk",
    "DSTOCK": "FhhXCnCbxBQ4nX4a4PBTuYG3gbETWixoNejQkPKJbonk",
    "JOJO": "4RwVoEESmPWWXG1wJGgpbapYsRdfB2Q3mVHkYXtLbonk",
    "rudi": "2rVgh6tcU1Hhk58XwD631E2D6iqLV28prSdpBXaLbonk",
    "BUMPER": "5bp5PwTyu4i1hGyQsRwRYqiR2CmxyHt2cPJGEbXEbonk",
    "WIREBACK": "29EyhwxrwUMp5JFSjAaTg78ffRn8S7DxtbzYjSVbbonk",
    "Dale": "HjjmgBxtnu7soQfbyQAi3ZJAo8MPAA9rn6EPN2K9bonk",
    "gib": "6FtbGaqgZzti1TxJksBV4PSya5of9VqA9vJNDxPwbonk",
    "Bonkyo": "oha3mwwm2tqWRouJ2KGUiz4Vz9FCRcPm1fApm87bonk",
    "DEBT": "vLieQF5eDqUuuk8RzRaqgAHkXr7bSEBZaWk9Zfibonk",
    "quby": "Hdmx6XcGyWNdEwYGcBaAQLYWgniiea7ioPCgzknkbonk",
    "BYTE": "Fh7aoHJgToiFr93RLb274bG9gTymEMdGGHrHdUhEbonk",
    "CRCL": "HyU6PuA4oDPxnEpP7E3MGc4u6MQ4m31LZihTF7RPbonk",
    "LNS": "HyapM8zt9vex1Nc1KXd5teiHMzd7y5nhcnHEwk81bonk",
    "Priceless": "2MftFt6Ci6Tht2BmvRppiVJmrtCVB5rUC8SEa2J9bonk",
    "XAI": "PreYPq1LdVBhKsYC3nRmZW5Y9yJXwSuDYmUSikFCwGS",
    "IMFOOD": "PreQhJLE9YMSVtJpVLJ3bAWE2BQ5AqBniG7aA2bGRRz",
    "SARONC": "PreJuqZjkL2QFkx78MkEGv8P6Zk8qqpTx9GSjLtfvXW",
    "ANDURL": "Prep57BLk9uKWRzKigtQBbrYFxcDXtHuCjxFRM5UXAS",
    "OPENAI": "PreYKD2kJ5xGgoZ644VPfbEN7sW8bWCUREHr5S3ebV9",
    "GROQ": "Pre8wtN7sLADKn8qekjQipcSiYTGg5tafWqeH49s1wQ",
    "GLEAN": "PreZdBV5d4XDUa7diCGZmyZXQSpbAdrTEzmgvUWY5Dd",
    "DATABR": "PregdTtARmfoDGB7XsbyyZc4RmKbKdmiPFXvinBpjTa",
    "ADEPAR": "PreDmU41w1LZaDqiEQdd75ffWaDndMMN8bJPfNno4AM",
    "ANTHRP": "PreGERrFuZAJqTxJ5oC3DeQmfdrniNzJgqKGFb2ZLE6",
    "CHAOS": "PrejfFQH6y6aQBfR43zuBqnPXvQrDU5EugwVEBQZVK3",
    "SSI": "Pre2Y4gaf97C4T8ckygDpYbja3w6mH6zmCEs3SA8ALH",
    "PPLXTY": "PreG98Hxr4GNswTNTQfBVqRQe6DNCjJ9Rg5jqFzmiXA",
    "DISCRD": "PrekBgzytydXoDTrH5NW9ABP68c96twxML8oV1NnV8d",
    "APTRNK": "PreZsfo4N5J16vpJWvaTubLpNHrBe1fNgvoFuqZ21xK",
    "FIGURE": "PreAYsissANcRXg5uTniKqdCrrUSGdvtrKDVPHS1ib6",
    "EPIC": "PreGJxNkwFp8KmtA5rnvgv2z3zAa8c2UQMfN4FjPh4Z",
    "SPACEX": "Preb5VKsmKgMGhMKUhDpe7A2AhMDmrZtMMZmvFEhLbU",
    "KRAKEN": "Pres43hQWdY6HaHWckmgzqyQgVwYCXen3VPrXMoKWeY",
    "NEURAL": "Pre5X98d9ZvgGirEcWqeCVDK6wQ52stKkmU3HsH6bfE",
    "HARVEY": "PrevLYRs2HreKvo2bEQsAo839m38ws5TH2WHYFzqsWt",
    "BLABLA": "PreQ1REpwo4v5d8QMF58h3jpqKww9k5NMbvBXMVo7A5",
}

TOKEN_PROGRAMS = {
    "default": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
    "2022": "TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb",
}

TOKENS_PROGRAM = {
    "USDC": "default",
    "USDT": "default",
}


address_locks = defaultdict(asyncio.Lock)
